// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: owVdPvEphTbmsFvPUSwECY
// Component: WnTO2axET2_0X
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import IconLink from "../../IconLink"; // plasmic-import: n1q1P7iULA40pt/component
import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: uYbqYp8q9yY0/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_furn_e_commerce.module.css"; // plasmic-import: owVdPvEphTbmsFvPUSwECY/projectcss
import * as sty from "./PlasmicFooter.module.css"; // plasmic-import: WnTO2axET2_0X/css
import LocationArrowIcon from "./icons/PlasmicIcon__LocationArrow"; // plasmic-import: _W7VGDybmD9dS/icon
import FacebookIcon from "./icons/PlasmicIcon__Facebook"; // plasmic-import: ZBHqOM1ZnERRc/icon
import InstagramIcon from "./icons/PlasmicIcon__Instagram"; // plasmic-import: oY1GmiHrp50L3/icon
import LinkedinIcon from "./icons/PlasmicIcon__Linkedin"; // plasmic-import: ueUNbpfiz0itQ/icon

export const PlasmicFooter__VariantProps = new Array();

export const PlasmicFooter__ArgProps = new Array();

function PlasmicFooter__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(defaultcss.all, sty.box__uzC)}
      >
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(defaultcss.all, sty.box__cyfV)}
        >
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__vHl0G
            )}
          >
            {"Information"}
          </div>

          <div className={classNames(defaultcss.all, sty.box__llw4O)}>
            <a
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.link__qw5WR
              )}
              href={"#"}
            >
              {"About Us"}
            </a>

            <a
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.link___4XyZu
              )}
              href={"#"}
            >
              {"Contact Us"}
            </a>

            <a
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.link__rau6L
              )}
              href={"#"}
            >
              {"News"}
            </a>

            <a
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.link__pfOcj
              )}
              href={"#"}
            >
              {"Store"}
            </a>
          </div>
        </p.Stack>

        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(defaultcss.all, sty.box___9WHwR)}
        >
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__t6RIh
            )}
          >
            {"Collections"}
          </div>

          <div className={classNames(defaultcss.all, sty.box__q7RaT)}>
            <a
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.link__dUjo
              )}
              href={"#"}
            >
              {"Wooden Chair"}
            </a>

            <a
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.link__liJdp
              )}
              href={"#"}
            >
              {"Royal Cloth Sofa"}
            </a>

            <a
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.link__bAm8S
              )}
              href={"#"}
            >
              {"Accent Chair"}
            </a>

            <a
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.link__qY1Cb
              )}
              href={"#"}
            >
              {"Bed"}
            </a>

            <a
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.link__awLf
              )}
              href={"#"}
            >
              {"Hanging Lamp"}
            </a>
          </div>
        </p.Stack>

        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(defaultcss.all, sty.box___9XcZd)}
        >
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__fOcEs
            )}
          >
            {"My Accounts"}
          </div>

          <div className={classNames(defaultcss.all, sty.box__mTsO4)}>
            <a
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.link__oeSjR
              )}
              href={"#"}
            >
              {"My Account"}
            </a>

            <a
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.link___3L1Mk
              )}
              href={"#"}
            >
              {"Wishlist"}
            </a>

            <a
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.link__jd8DS
              )}
              href={"#"}
            >
              {"Community"}
            </a>

            <a
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.link__f9P61
              )}
              href={"#"}
            >
              {"Order History"}
            </a>

            <a
              className={classNames(
                defaultcss.all,
                defaultcss.__wab_text,
                sty.link__yx55
              )}
              href={"#"}
            >
              {"My Cart"}
            </a>
          </div>
        </p.Stack>

        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(defaultcss.all, sty.box___4TTjl)}
        >
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__nqP2G
            )}
          >
            {"Newsletter"}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box__ajBVt
            )}
          >
            {"Subscribe to get latest news, updates, and information"}
          </div>

          <div className={classNames(defaultcss.all, sty.box__y8F0G)}>
            <input
              data-plasmic-name={"textbox"}
              data-plasmic-override={overrides.textbox}
              className={classNames(defaultcss.input, sty.textbox)}
              placeholder={"Enter Email Here..."}
              size={1}
              type={"text"}
              value={""}
            />

            <IconLink
              className={classNames("__wab_instance", sty.iconLink__krCu)}
              icon={
                <LocationArrowIcon
                  className={classNames(defaultcss.all, sty.svg___5KzOd)}
                  role={"img"}
                />
              }
            />
          </div>
        </p.Stack>
      </p.Stack>

      <div className={classNames(defaultcss.all, sty.box__tNvaM)}>
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(defaultcss.all, sty.box__tsMaW)}
        >
          <IconLink
            className={classNames("__wab_instance", sty.iconLink__ajuMw)}
            icon={
              <FacebookIcon
                className={classNames(defaultcss.all, sty.svg__zkm4A)}
                role={"img"}
              />
            }
          />

          <IconLink
            className={classNames("__wab_instance", sty.iconLink__fL3HK)}
            icon={
              <InstagramIcon
                className={classNames(defaultcss.all, sty.svg__hGvut)}
                role={"img"}
              />
            }
          />

          <IconLink
            className={classNames("__wab_instance", sty.iconLink__mt0S4)}
            icon={
              <LinkedinIcon
                className={classNames(defaultcss.all, sty.svg___8YkA)}
                role={"img"}
              />
            }
          />
        </p.Stack>

        <div className={classNames(defaultcss.all, sty.box__h7BFt)}>
          <div
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.box___241Km
            )}
          >
            {"© Copyright. "}
          </div>

          <a
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.link__uEVa
            )}
            href={"https://www.plasmic.app/"}
          >
            {"Made by Plasmic. "}
          </a>

          <a
            className={classNames(
              defaultcss.all,
              defaultcss.__wab_text,
              sty.link__wkvms
            )}
            href={"https://www.themesine.com/"}
          >
            {"Inspired by Themesine."}
          </a>
        </div>
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "textbox"],
  textbox: ["textbox"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFooter__ArgProps,
      internalVariantPropNames: PlasmicFooter__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicFooter__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFooter";
  } else {
    func.displayName = `PlasmicFooter.${nodeName}`;
  }
  return func;
}

export const PlasmicFooter = Object.assign(
  // Top-level PlasmicFooter renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    textbox: makeNodeComponent("textbox"),
    // Metadata about props expected for PlasmicFooter
    internalVariantProps: PlasmicFooter__VariantProps,
    internalArgProps: PlasmicFooter__ArgProps
  }
);

export default PlasmicFooter;
/* prettier-ignore-end */
