// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: owVdPvEphTbmsFvPUSwECY
// Component: Wxr8hD3Wuh02fH
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_furn_e_commerce.module.css"; // plasmic-import: owVdPvEphTbmsFvPUSwECY/projectcss
import * as sty from "./PlasmicRatings.module.css"; // plasmic-import: Wxr8hD3Wuh02fH/css
import StarIcon from "./icons/PlasmicIcon__Star"; // plasmic-import: c0CQ3Fk7qloT5/icon

export const PlasmicRatings__VariantProps = new Array("stars");

export const PlasmicRatings__ArgProps = new Array("numReviews");

function PlasmicRatings__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root, {
        [sty.root__stars_five]: hasVariant(variants, "stars", "five"),
        [sty.root__stars_four]: hasVariant(variants, "stars", "four"),
        [sty.root__stars_one]: hasVariant(variants, "stars", "one"),
        [sty.root__stars_three]: hasVariant(variants, "stars", "three"),
        [sty.root__stars_two]: hasVariant(variants, "stars", "two"),
        [sty.root__stars_zero]: hasVariant(variants, "stars", "zero")
      })}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"box"}
        data-plasmic-override={overrides.box}
        hasGap={true}
        className={classNames(defaultcss.all, sty.box)}
      >
        {(hasVariant(variants, "stars", "zero") ? false : true) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__rcDuZ, {
              [sty.svg__stars_five__rcDuZsej5A]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svg__stars_zero__rcDuZvsNmk]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? false
            : false
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__oOcY, {
              [sty.svg__stars_five__oOcYsej5A]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svg__stars_four__oOcYgUodQ]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svg__stars_one__oOcY9Be7E]: hasVariant(
                variants,
                "stars",
                "one"
              ),

              [sty.svg__stars_three__oOcYhRnSd]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svg__stars_two__oOcYe8N0Y]: hasVariant(
                variants,
                "stars",
                "two"
              ),

              [sty.svg__stars_zero__oOcYvsNmk]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? false
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? false
            : false
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__uzGP, {
              [sty.svg__stars_five__uzGPsej5A]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svg__stars_four__uzGPgUodQ]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svg__stars_one__uzGP9Be7E]: hasVariant(
                variants,
                "stars",
                "one"
              ),

              [sty.svg__stars_three__uzGPhRnSd]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svg__stars_two__uzGPe8N0Y]: hasVariant(
                variants,
                "stars",
                "two"
              ),

              [sty.svg__stars_zero__uzGPvsNmk]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? false
            : hasVariant(variants, "stars", "two")
            ? false
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? false
            : false
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__iIIrH, {
              [sty.svg__stars_five__iIIrHsej5A]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svg__stars_four__iIIrHgUodQ]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svg__stars_one__iIIrH9Be7E]: hasVariant(
                variants,
                "stars",
                "one"
              ),

              [sty.svg__stars_three__iIIrHhRnSd]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svg__stars_two__iIIrHe8N0Y]: hasVariant(
                variants,
                "stars",
                "two"
              ),

              [sty.svg__stars_zero__iIIrHvsNmk]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? false
            : hasVariant(variants, "stars", "three")
            ? false
            : hasVariant(variants, "stars", "two")
            ? false
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? false
            : false
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg___3N5P, {
              [sty.svg__stars_five___3N5Psej5A]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svg__stars_four___3N5PGUodQ]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svg__stars_one___3N5P9Be7E]: hasVariant(
                variants,
                "stars",
                "one"
              ),

              [sty.svg__stars_three___3N5PHRnSd]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svg__stars_two___3N5PE8N0Y]: hasVariant(
                variants,
                "stars",
                "two"
              ),

              [sty.svg__stars_zero___3N5PVsNmk]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? false
            : hasVariant(variants, "stars", "four")
            ? false
            : hasVariant(variants, "stars", "three")
            ? false
            : hasVariant(variants, "stars", "two")
            ? false
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? true
            : false
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__vjXrE, {
              [sty.svg__stars_five__vjXrEsej5A]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svg__stars_four__vjXrEgUodQ]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svg__stars_one__vjXrE9Be7E]: hasVariant(
                variants,
                "stars",
                "one"
              ),

              [sty.svg__stars_three__vjXrEhRnSd]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svg__stars_two__vjXrEe8N0Y]: hasVariant(
                variants,
                "stars",
                "two"
              ),

              [sty.svg__stars_zero__vjXrEvsNmk]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? false
            : hasVariant(variants, "stars", "four")
            ? false
            : hasVariant(variants, "stars", "three")
            ? false
            : hasVariant(variants, "stars", "two")
            ? false
            : true
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg___6Lnkj, {
              [sty.svg__stars_five___6Lnkjsej5A]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svg__stars_four___6LnkjGUodQ]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svg__stars_three___6LnkjHRnSd]: hasVariant(
                variants,
                "stars",
                "three"
              ),

              [sty.svg__stars_two___6LnkjE8N0Y]: hasVariant(
                variants,
                "stars",
                "two"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? false
            : hasVariant(variants, "stars", "four")
            ? false
            : hasVariant(variants, "stars", "three")
            ? false
            : true
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__ywjaw, {
              [sty.svg__stars_five__ywjawsej5A]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svg__stars_four__ywjawGUodQ]: hasVariant(
                variants,
                "stars",
                "four"
              ),

              [sty.svg__stars_three__ywjawHRnSd]: hasVariant(
                variants,
                "stars",
                "three"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? false
            : hasVariant(variants, "stars", "four")
            ? false
            : true
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__ugRyk, {
              [sty.svg__stars_five__ugRyKsej5A]: hasVariant(
                variants,
                "stars",
                "five"
              ),

              [sty.svg__stars_four__ugRykgUodQ]: hasVariant(
                variants,
                "stars",
                "four"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(hasVariant(variants, "stars", "five") ? false : true) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__zfl5S, {
              [sty.svg__stars_five__zfl5Ssej5A]: hasVariant(
                variants,
                "stars",
                "five"
              )
            })}
            role={"img"}
          />
        ) : null}
      </p.Stack>

      {p.renderPlasmicSlot({
        defaultContents: "(45 Review)",
        value: args.numReviews,
        className: classNames(sty.slotNumReviews)
      })}
    </p.Stack>
  );
}

const PlasmicDescendants = {
  root: ["root", "box"],
  box: ["box"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicRatings__ArgProps,
      internalVariantPropNames: PlasmicRatings__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicRatings__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRatings";
  } else {
    func.displayName = `PlasmicRatings.${nodeName}`;
  }
  return func;
}

export const PlasmicRatings = Object.assign(
  // Top-level PlasmicRatings renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    box: makeNodeComponent("box"),
    // Metadata about props expected for PlasmicRatings
    internalVariantProps: PlasmicRatings__VariantProps,
    internalArgProps: PlasmicRatings__ArgProps
  }
);

export default PlasmicRatings;
/* prettier-ignore-end */
